# Generated by Django 5.1.6 on 2025-04-17 17:56

import api.models.user_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_console_image_laptop_image_pc_image_phone_image_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', api.models.user_models.CustomUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.models.user_models.CustomUserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
            managers=[
                ('objects', api.models.user_models.CustomUserManager()),
            ],
        ),
    ]
