# Generated by Django 5.1.6 on 2025-04-20 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cart_includes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('laptop', 'Laptop'), ('pc', 'PC'), ('tv', 'TV'), ('phone', 'Phone'), ('console', 'Console'), ('video_game', 'Video Game'), ('accessory', 'Accessory')], max_length=20)),
                ('product_id', models.PositiveIntegerField()),
                ('percent_discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.admin')),
            ],
            options={
                'unique_together': {('product_type', 'product_id', 'admin')},
            },
        ),
    ]
