# Generated by Django 5.1.6 on 2025-04-18 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_accessory_console_brand_laptop_brand_pc_brand_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Console',
        ),
        migrations.DeleteModel(
            name='Video_Game',
        ),
    ]
