# Generated by Django 5.1.6 on 2025-04-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_console_video_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_game',
            name='genre',
            field=models.CharField(max_length=25),
        ),
    ]
