# Generated by Django 5.2 on 2025-04-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_video_game_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Includes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('product_id', models.IntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'unique_together': {('customer_email', 'product_id')},
            },
        ),
    ]
